#!/usr/bin/env sh

INSTALL=false 
UPDATE=true
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while getopts 'iu' flag; do
  case "${flag}" in
    i) INSTALL=true ;;
    u) UPDATE=true ;;
    *) error "Unexpected option ${flag}" ;;
  esac
done

if $INSTALL; then
  echo "Installing first configuration\n"

  if [ "$(uname)" == "Darwin" ]; then
    . "$DOTFILES_DIR/osx/install.sh"
  elif [ "$(uname)" == "Linux" ]; then
    . "$DOTFILES_DIR/antergos/install.sh"
  fi
fi

if $UPDATE; then 
  echo "\nInstalling dotfiles\n"

  ln -sfv "$DOTFILES_DIR/git/.gitconfig" ~
  ln -sfv "$DOTFILES_DIR/git/.gitignore_global" ~
fi